name: Python Testing
on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        # python-version: [3.9,3.10,3.11]
        python-version: [3.11]
    name: Test
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Env
        uses: actions/setup-python@v4
        with: 
          python-version: ${{matrix.python-version}}
      - name: Install deps
        run: python -m pip install pytest

      - name: Run Tests
        run: pytest